---
meta:
  size: default
  default:
    azs: [z1]
  password: (( vault $CREDENTIALS "/redis/system:password" ))

releases:
  - { name: redis-forge, version: latest }

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: standalone
    instances: 1
    azs: (( grab meta.azs || meta.default.azs ))
    networks: [name: (( grab meta.net || 'redis-service' ))]
    stemcell: default

    vm_type: (( grab meta.size ))
    persistent_disk: (( grab meta.disk || 0 ))

    jobs:
      - name:    standalone
        release: redis-forge
        properties:
          auth:
            password: (( grab meta.password ))
          persistent: (( grab meta.persistent ))
